import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/providers/store.provider";
import AuthProvider from "@/components/providers/auth.provider";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-spaceGrotesk",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} ${spaceGrotesk.className}`}>
        <StoreProvider>
          <AuthProvider>
            <main>{children}</main>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
